### ISSUE TITLE
не работает /delete-reply

### ISSUE THREAD

**Issue by YasuArai** [AndreyDaniluk/OpenHavroniyaTelegram#1]
![image](https://user-images.githubusercontent.com/108483846/176733460-8b6c01fe-4e5d-4f58-9d49-d9cb255e5988.png)
![image](https://user-images.githubusercontent.com/108483846/176733596-4ec9daef-230c-45cf-8697-1d075cf16481.png)

**Comment by AndreyDaniluk** [comment]
Исправлено. Обновите файл tg.py из этого репозитория
